[audio]
enable_sounds = true
sound_volume = 0.29999999329447746

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.99999997764825821
    border = "primary"
    border_width = 0.5
    capsule = false
    capsule_thickness = 0.54999999143183231
    center = [ "group:g4" ]
    end = [ "tray", "group:g1", "group:g2", "group:g3", "spacer_3" ]
    margin_ends = 0
    padding = 0
    position = "bottom"
    radius = 0
    scale = 1.0000000074505806
    shadow = false
    start = [ "spacer_2", "media", "workspaces" ]
    thickness = 40
    widget_spacing = 8

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "primary"
        foreground = "on_primary"
        id = "g1"
        members = [ "network", "bluetooth" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "secondary"
        foreground = "on_primary"
        id = "g2"
        members = [ "volume", "input_volume", "brightness", "battery" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "outline"
        foreground = "on_surface"
        id = "g3"
        members = [ "clipboard", "notifications", "control-center", "session" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = ""
        enabled = true
        fill = "secondary"
        foreground = "on_secondary"
        id = "g4"
        members = [ "wallpaper", "clock", "date" ]
        opacity = 1.0
        padding = 8.0
        widget_spacing = 10

[control_center.calendar]
show_events_card = false

[keybinds]
down = [ "down", "ctrl+n" ]
up = [ "up", "ctrl+p" ]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@WL-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@WL-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 468.0
    cy = 948.0
    output = "WL-1"
    placement_height = 1130.0
    placement_width = 936.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WL-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 972.5
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
force = true

[plugins]
enabled = [ "weinguyen/procmon" ]

[shell]
lang = "en"
polkit_agent = true

    [shell.panel]
    clipboard_placement = "floating"
    control_center_placement = "floating"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    session_placement = "floating"
    transparency_mode = "solid"
    wallpaper_placement = "floating"

[theme]
builtin = "Nord"
community_palette = "Doomed"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/mmk/pictures/wallpapers"

    [wallpaper.default]
    path = "/home/mmk/pictures/wallpapers/wallpaper3.png"

    [wallpaper.last]
    path = "/home/mmk/pictures/wallpapers/wallpaper3.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/mmk/pictures/wallpapers/wallpaper3.png"

[widget.media]
capsule = true
capsule_border = "outline"
capsule_padding = 10
hide_when_no_media = true
title_scroll = "on_hover"

[widget.notifications]
capsule_fill = "on_secondary"
capsule_foreground = "secondary"

[widget.session]
enabled = false

[widget.spacer_2]
length = 10
type = "spacer"

[widget.spacer_3]
length = 10
type = "spacer"

[widget.tray]
capsule = true
capsule_fill = "tertiary"
capsule_opacity = 0.66000000000000003
capsule_padding = 5
capsule_radius = 3
scale = 1.3500000000000001

[widget.workspaces]
capsule = true
capsule_fill = "outline"
